jobs:
  - name: daily model runs
    targetName: dev
    schedule:
      type: integrated
      integrations:
        - 
    timeout: 2h30m
    retryOnFailure: true
    steps:
      - name: run models
        command: dbt run
      - name: test models
        command: dbt test
